name: mini_games
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.2
  crypto: ^3.0.3
  flutter_bcrypt: ^1.0.8
  bcrypt: ^1.1.3
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/shifumi.jpg
    - assets/morpion.jpg
    - assets/chess.jpg
    - assets/solitaire.jpg
    - assets/blackjack.jpg
    - assets/sudoku.jpg

